### ISSUE TITLE
Make the input of loggers more general

### ISSUE THREAD

**Issue by facundominguez** [tweag/smtlib-backends#13]
Currently, logging messages are prepended with tags like `[send] `, `[recv] `, `[stderr] `. Liquid Haskell prepends nothing to queries, and `;` to responses, so the logs ends up in a file that can be fed to `z3` without further processing.

Either these tags need to be documented in the interface of the `log` function, or a proper parameter should be provided to convey the meaning instead of prepending to the message. e.g. `log :: LogType -> ByteString -> IO ()` with `data LogType = Send | Recv`.

**Comment by qaristote** [comment]
I agree to say this is needed, but I'm not sure of the best way to actually implement that. Your proposal sounds good if we only make this change for the `Solver`'s logger, not the backend ones (I'd be fine with this). 

But if we extend the change to backends, should each backend provide its own `LogType` datatype ? That doesn't sound great, because the user would have to reimplement a logger function for each backend. But sharing the datatype doesn't sound too good either, because log types specific to a single backend would pollute the overall datatype for all the other backends.

Would it be fine with Liquid Haskell if the backend logger just printed error messages without prefixes ?

**Comment by facundominguez** [comment]
> Would it be fine with Liquid Haskell if the backend logger just printed error messages without prefixes?

This works for now.

> Your proposal sounds good if we only make this change for the Solver's logger,

This would work for now.

> That doesn't sound great, because the user would have to reimplement a logger function for each backend.

This is the case already. Each backend can be initialized with some logging function of type `ByteString -> IO ()`. The type happens to be the same in the two backends we have, but there is nothing preventing the implementor of a backend to use a different type for the logging function, or to offer no way at all to do logging.
