### ISSUE TITLE
`Backends`: follow the Handle design pattern

### ISSUE THREAD

**Issue by qaristote** [tweag/smtlib-backends#31]
Using the library is currently a bit awkward:
```haskell
initSolver backend True
```
isn't clear about what `True` means here.
The `Solver` datatype's name is also awkward because it is usually used to define higher-level `Solver` datatypes.

Using the Handle design pattern should solve these problems, but they are still a few things to decide upon, namely on what to do with the `Backend` datatype:
- should it go inside its own module as a Handle itself ?
- since the solver will get its own `close` method, should we add `new` and `close` to the `Backend` signature so that we have a unified interface for initializing backends ?

**Comment by facundominguez** [comment]
> isn't clear about what True means here.

The idiomatic way to deal with this is to define a datatype `data QueueingFlag = Queuing | NotQueueing` instead of using `Bool`.

> since the solver will get its own close method, should we add new and close to the Backend signature so that we have a unified interface for initializing backends ?

I think there is little benefit for including initialization, it would force all backends to be initialized in a common scheme for no good reason. Finalization could perhaps be part of the Backend, so finishing the solver does finish the backend.

> The Solver datatype's name is also awkward because it is usually used to define higher-level Solver datatypes.

The only thing the solver is doing is implementing queuing. It could be renamed to `SMTLIBQueue`, or `SolverQueue`, or `CommandQueue`.

Another way eliminate the ambiguity in the name is to always import the Solver type and its functions with some qualified name to distinguish it from other Solver's in an application. But it is a concern of the application, not of the library, since there might be no other Solver type around.

> should it go inside its own module as a Handle itself ?

Since Backend is an interface and not an implementation of one, I think the Handle pattern does not apply so well to it.

**Comment by facundominguez** [comment]
> Finalization could perhaps be part of the Backend, so finishing the solver does finish the backend.

But on the other hand, it makes sense for the code initializing the Backend to deal with setting up the clean up, and not splitting the responsibility of managing the resource lifespan between the backend API and the Solver API.

**Comment by qaristote** [comment]
I'm looking into plugging-in `smtlib-backends` into `liquid-fixpoint` right now and I think this is an example where having a `close` method in the `Backend` datatype could be useful: `liquid-fixpoint` doesn't use a `with` function, but rather separates initialization and garbage collection into two functions ([`makeProcess`](https://github.com/ucsd-progsys/liquid-fixpoint/blob/c597c2ba3554ddfcf787cca45ee2e2d2ed984d76/src/Language/Fixpoint/Smt/Interface.hs#L311-L336) and [`hClose`](https://github.com/ucsd-progsys/liquid-fixpoint/blob/c597c2ba3554ddfcf787cca45ee2e2d2ed984d76/src/Language/Fixpoint/Smt/Interface.hs#L347-L348)). This means that in practice you have to carry around both the `Solver` instance and the `Process.Handle` instance, which I already find awkward, but to add insult to injury if you want to leave the option to use other backends than you have to define a new datatype such as `BackendHandle = Process Process.Handle | Z3API Z3.Handle` so that you can accomodate for carrying around both types of handles.

> The idiomatic way to deal with this is to define a datatype data QueueingFlag = Queuing | NotQueueing instead of using Bool.

Sounds good, I'll implement this.

**Comment by qaristote** [comment]
> Another way to eliminate the ambiguity in the name is to always import the Solver type and its functions with some qualified name to distinguish it from other Solver's in an application. But it is a concern of the application, not of the library, since there might be no other Solver type around.

This is what I've been doing so far but I'm not completely satisfied of how I've been naming the `SMTLIB.Backend` module: I've been using `Bck` (for `Backend`) but `Bck.Solver` might be a bit confusing (is it the solver or the backend ?). But this is just me nitpicking, it's only a very minor issue.
